name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sync
        uses: patrickwyler/gcs-bucket-sync-action@1.3
        with:
          secrets: ${{ secrets.google_service_account_credentials }}
          bucket: 'base2code'
          exclude: '.*\.md$|\.gitignore$|\.git/.*$|\.github/.*$|\..*|LICENSE$|package.json$|package-lock.json$|sass/.*$'
